#!/bin/sh
bspc rule -r "*"

###---Autostart---###
sxhkd &
xset r rate 300 50 &
xset s off -dpms &
xrdb ~/.Xresources &
xcompmgr &
~/.config/fixmonitors.sh &
feh --bg-scale ~/.config/wallpaper &
~/.config/polybar/launch.sh &
xmodmap ~/.Xmodmap &
/usr/bin/emacs --daemon &

###---MONITORS---###
bspc monitor DP-3 -d 7 8 9
bspc monitor DP-1 -d 1 2 3
bspc monitor DVI-D-1 -d 4 5 6

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color     "#4c566a"
bspc config active_border_color     "#1e1e1e"
bspc config focused_border_color "$WINDOWMANAGER_CUSTOM_COLOR"
bspc config presel_feedback_color   "#5e81ac"
bspc config urgent_border_color "$POLYBAR_ALERT_COLOR"

###---Monitor And Desktop Settings----###
bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 12


### Rules
bspc rule -a emacs state=tiled
