#!/usr/bin/env sh

export DMENU_CUSTOM_NF="#ffffff"
export DMENU_CUSTOM_NB="$(gethex background)"
export DMENU_CUSTOM_SB="#303030"
export DMENU_CUSTOM_SF="$(gethex cyan)"
export DMENU_PROMPT_COLOR="$(gethex cyan)"
export DMENU_ARGUMENTS="-nb $DMENU_CUSTOM_NB -nf $DMENU_CUSTOM_NF -sb $DMENU_CUSTOM_SB -sf $DMENU_CUSTOM_SF -i"
