#!/usr/bin/env sh

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

#Gnome keyring auto-unlock
eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

exec dwm
