#!/usr/bin/env sh

run() {
    ! pidof $1 > /dev/null 2>&1 && $1 &
}

# Changes some X settings
xset r rate 300 50 &
xset s off -dpms &

# Uses xrdb to set the colors
xrdb "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources" &

# Switch Capslock with L-CTRL for a better emacs experience
xmodmap "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xmodmap" &

# Fixes monitor placement and resolution
~/.config/fixmonitors.sh &

# Starts the emacs daemon
killall emacs
/usr/bin/emacs --daemon &

# Starts the statusbar
run dwmblocks

# Compositor
run xcompmgr

# Sets wallpaper
run setbg

# Changes the window manager name to let Java IDEs to run
wmname "LG3D" &

# Starts the transmission daemon if not already started
run transmission-daemon
