#!/usr/bin/env sh

run() {
    ! pidof $1 > /dev/null 2>&1 && $1 $@ &
}

# Changes some X settings
xset r rate 300 50 &
xset s off -dpms &

# Uses xrdb to set the colors
xrdb "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources" &

# Switch Capslock with L-CTRL for a better emacs experience
#xmodmap "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xmodmap" &

# Fixes monitor placement and resolution
~/.config/fixmonitors.sh &

# Starts the emacs daemon
killall emacs
/usr/bin/emacs --daemon &

# Starts the statusbar
# run dwmblocks
~/.dwm/bar &

# Starts mpd
pidof mpd || mpd &

# Compositor
killall picom
picom --experimental-backends &

# Sets wallpaper
run setbg

# Update the volume module because after reboots it likes to get stuck
(sleep 5s && pkill -RTMIN+3 dwmblocks) &

#trayer --edge top --align right --widthtype request --padding 6 --SetDockType true --SetPartialStrut true --expand true --transparent true --alpha 0 --tint 0x1e1e1e  --height 22 &
# Changes the window manager name to let Java IDEs to run
# wmname "LG3D" &

# Launch pipewire
dbus-launch --sh-syntax --exit-with-session; pulseaudio --kill; pipewire &
