#!/usr/bin/env sh

run() {
	! pidof $1 >/dev/null 2>&1 && $1 $@ &
}

# Changes some X settings
xset r rate 300 50 &
xset s off -dpms &

# Uses xrdb to set the colors
xrdb "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources" &

# Switch Capslock with L-CTRL for a better emacs experience
#xmodmap "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xmodmap" &

# Automount USBs
killall udiskie
udiskie &

# Fixes monitor placement and resolution
#~/.config/fixmonitors.sh &
nvidia-settings --load-config-only &

# Starts the emacs daemon
killall emacs
/usr/bin/emacs --daemon &

# Starts the statusbar
run dwmblocks
# Update the volume module because after reboots it likes to get stuck
(sleep 5s && pkill -RTMIN+3 dwmblocks) &

#slstatus &

# Starts mpd
pidof mpd || mpd &

# Sets wallpaper
run setbg

# Changes the window manager name to let Java IDEs to run
(sleep 5s && wmname "LG3D" &)

# Notifications
killall dunst
dunst &

# Launch pipewire
# dbus-launch --sh-syntax --exit-with-session; pulseaudio --kill; pipewire &

# Polkit
killall polkit-dumb-agent
/usr/bin/polkit-dumb-agent &

# Nextcloud
#pidof nextcloud >/dev/null 2>&1 || nextcloud --background &
