#!/usr/bin/env sh

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for x in mount umount updatedb su pacman; do
    alias $x="sudo $x"
done

# Verbosity and settings that you pretty much just always are going to want.
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    bc="bc -ql" \
    mkdir="mkdir -pv" \
    ffmpeg="ffmpeg -hide_banner"

# Pacman stuff
# alias \
#     cleanup='sudo pacman -Rns $(pacman -Qtdq)' \
#     p='paru' \
#     P='pacman'
#
# pf() {
#     paru -Sl \
#         | awk '{print $2($4=="" ? "" : " *")}' \
#         | fzf -q "$1" -m --preview 'cat <(echo {1} | cut -d " " -f 1 | paru -Si -) <(echo {1} | cut -d " " -f 1 | paru -Fl - | awk "{print $2}")' \
#         | cut -d " " -f 1 \
#         | xargs -ro paru -S
# }

# youtube-dl
alias yta-aac="youtube-dl --extract-audio --audio-format aac "
alias yta-best="youtube-dl --extract-audio --audio-format best "
alias yta-flac="youtube-dl --extract-audio --audio-format flac "
alias yta-m4a="youtube-dl --extract-audio --audio-format m4a "
alias yta-mp3="youtube-dl --extract-audio --audio-format mp3 "
alias yta-opus="youtube-dl --extract-audio --audio-format opus "
alias yta-vorbis="youtube-dl --extract-audio --audio-format vorbis "
alias yta-wav="youtube-dl --extract-audio --audio-format wav "
alias ytv-best="youtube-dl -f bestvideo+bestaudio "

# soystemD
# alias \
#     S="sudo systemctl"

# Portage stuff
alias \
    eu="sudo emerge -vuDU --with-bdeps=y @world" \
    eum="sudo emerge -vuDU --autounmask-continue --with-bdeps=y @world" \
    es="sudo eix-sync" \
    e="sudo emerge" \
    em="sudo emerge --autounmask-continue"

# Flaggie
alias \
    f="sudo flaggie"

# Equery shortening
alias \
    eqf='equery f' \
    equ='equery u' \
    eqh='equery h' \
    eqa='equery a' \
    eqb='equery b' \
    eql='equery l' \
    eqd='equery d' \
    eqg='equery g' \
    eqc='equery c' \
    eqk='equery k' \
    eqm='equery m' \
    eqy='equery y' \
    eqs='equery s' \
    eqw='equery w'

# Open-RC
alias \
    rcu="sudo rc-update" \
    rcs="sudo rc-service"

# CD stuff
alias \
    ..='cd ..' \
    ...='cd ../..' \
    .3='cd ../../..' \
    .4='cd ../../..' \
    .5='cd ../../../..' \
    .6='cd ../../../../..'

# Colorize commands when possible.
alias \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    egrep='egrep --color=auto' \
    fgrep='fgrep --color=auto'

# These common commands are just too long! Abbreviate them.
alias \
    ka="killall" \
    sdn="sudo shutdown -h now" \
    v="nvim" \
    c="vscode" \
    ef="e-file"

# LS aliases
alias \
    ls='lsd -al --color=always --group-dirs first' \
    la='lsd -a --color=always --group-dirs first' \
    ll='lsd -l --color=always --group-dirs first' \
    lt='lsd -aT --color=always --group-dirs first' \
    l.='lsd -a | egrep "^\."'

# Git aliases
alias \
    g='/usr/bin/git' \
    gs='/usr/bin/git status' \
    ga='/usr/bin/git add -u' \
    gaa='/usr/bin/git add .' \
    gc='/usr/bin/git commit -m' \
    gp="/usr/bin/git push origin master" \
    gpa="/usr/bin/git push gitlab master && /usr/bin/git push github master" \
    lg="lazygit"

# Applications
alias \
    z="devour zathura" \
    mpv="devour mpv" \
    cat="bat"

# University class folders
alias \
    m1140="$HOME/Nextcloud/School/KPU/Year-1/Term-1/MATH-1140/" \
    m1115="$HOME/Nextcloud/School/KPU/Year-1/Term-1/MATH-1115/" \
    i1113="$HOME/Nextcloud/School/KPU/Year-1/Term-1/INFO-1113/" \
    i1213="$HOME/Nextcloud/School/KPU/Year-1/Term-1/INFO-1213/" \
    i1214="$HOME/Nextcloud/School/KPU/Year-1/Term-1/INFO-1214/" \
    i1111="$HOME/Nextcloud/School/KPU/Year-1/Summer/INFO-1111/"

# Website updating
# alias webup="rsync -vrP --delete-after ~/.local/www/mccroryxyz/ root@mccrory.xyz:/var/www/mccrory"
webup() {
    folder=$(pwd | cut -d'/' -f6)
    /usr/bin/rsync -vrP --delete-after "$(pwd)/" "root@mccrory.xyz:/var/www/$folder"
}

# Make stuff
alias \
    smi="sudo make install" \
    msmi="make && sudo make install"

# fzf
se() {
    du -a ~/.local/bin/* ~/.config/* ~/.config/dmenu/scripts/* | awk '{print $2}' | fzf | xargs -r $EDITOR
}
