#!/usr/bin/env sh

### "bat" as manpager
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

### "nvim" as manpager
# export MANPAGER="nvim -c 'set ft=man' -"

# XDG Exports
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# Cleanup
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export XRESOURCES="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources"
export ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export ANSIBLE_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/ansible/ansible.cfg"
export UNISON="${XDG_DATA_HOME:-$HOME/.local/share}/unison"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export WEECHAT_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/weechat"
export ELECTRUMDIR="${XDG_DATA_HOME:-$HOME/.local/share}/electrum"
export WINEPREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/wineprefixes/default"
export LESSHISTFILE="-"

# Default Applications
export EDITOR="nvim"
export BROWSER="firefox-bin"
export TERMINAL="st"

# General
export PATH="$PATH:/home/jackson/.emacs.d/bin:$(find ~/.local/repos/dotfiles/home/.local/bin -type d -printf %p:)"
export QT_QPA_PLATFORMTHEME="qt5ct"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export SUDO_ASKPASS="$HOME/.config/dmenu/scripts/dmenu-pass.sh"
export MOZ_USE_XINPUT2="1"           # Mozilla smooth scrolling/touchpads.
export _JAVA_AWT_WM_NONREPARENTING=1 # Fix for Java applications in dwm

# Start the window manager
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg > /dev/null 2>&1 && exec startx "$XINITRC"
